version: '2'
services:
    db:
        image: mysql
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: <%= mysqlDatabase %>
            MYSQL_USER: root
            MYSQL_PASSWORD: root
    php:
        build: ./php
        expose:
            - "9000"
        volumes:
            - ./src:/var/www/<%= appName %>
        links:
            - db
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        links:
            - php
        volumes_from:
            - php
